export const CHANGE_DATA_BEGIN = "CHANGE_DATA_BEGIN";
export const CHANGE_DATA = "CHANGE_DATA";
export const CHANGE_DATA_FAILED = "CHANGE_DATA_FAILED";

export const TOGGLE_FORM = "TOGGLE_FORM";
export const CHANGE_PREVIEW = "CHANGE_PREVIEW";

export const ADMIN_FORM_INIT = "ADMIN_FORM_INIT";
export const ADMIN_FORM_SUCCESS = "ADMIN_FORM_SUCCESS";
export const ADMIN_FORM_FAILED = "ADMIN_FORM_FAILED";

export const DELETE_ENTRY_INIT = "DELETE_ENTRY_INIT";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_FAILED = "DELETE_ENTRY_FAILED";

